#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then







    xrdb -merge $sysresources

fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

if [ -f "$userresources" ]; then







    xrdb -merge "$userresources"

fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# I3
set lock after suspend/sleep
xss-lock -- /usr/local/bin/lock.sh &

# set keyboard to altgr variant no deadkeys
setxkbmap -rules evdev -model evdev -layout us -variant altgr-intl

# Desktop notification: https://wiki.archlinux.org/index.php/Dunst
# start udiskie to mount external storage automatically
udiskie &

# Set wallpaper
~/.fehbg &

# start i3
exec i3
