# local bin
export PATH="$PATH:$HOME/.local/bin:$HOME/tools/bin"

ZSH_THEME="agnoster"

source $HOME/.zplug/init.zsh
zplug "themes/agnoster", from:oh-my-zsh
# Vi mode in terminal
zplug "plugins/vi-mode", from:oh-my-zsh
# Automatically launch tmux
zplug "plugins/tmux", from:oh-my-zsh
# fish like syntax highlight
zplug "zsh-users/zsh-syntax-highlighting"
# fish like auto suggestion
zplug "zsh-users/zsh-autosuggestions"
# Jump to folder with Z
zplug "plugins/z", from:oh-my-zsh
# Move folder Ctrl+G
zplug "andrewferrier/fzf-z"
ZSH_TMUX_AUTOCONNECT=false
ZSH_TMUX_AUTOSTART=true

# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
zplug load

# zplug clean after plugin removal

source $(pew shell_config)
alias workon='pew workon'
alias mkvirtualenv='pew new'
alias rmvirtualenv='pew rm'

################## SHELL ################

# History file
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data
# Don't store command beginning with a space in history
setopt HIST_IGNORE_SPACE

# Automatically cd and push cd stack
setopt autocd autopushd pushdignoredups

# allow to do things like `ls *.png~not-this-file.png`
setopt extendedglob

export PAGER=less

# Vim as default editor
export EDITOR='vim'

# Access vi-mode using jk
bindkey -M viins 'jk' vi-cmd-mode

# Reverse search with C-r
bindkey '^R' history-incremental-search-backward

################## ALIAS ################
alias ..='cd ..'
# Set LS_COLORS
eval `dircolors`
alias ls='ls --color'
alias la='ls --color -la'
alias l='ls --color -l'
alias ll='ls --color -l'
alias grep='grep --color=auto'
alias v=vim
alias g=git
alias k=kubectl
alias gitk="gitk --all&"
alias -g pingme="; notify-send JOB FINISHED"

################## TOOLS ################

### Have current kube context on Rprompt
source "$HOME/kube-ps1/kube-ps1.sh"
RPROMPT='$(kube_ps1)'
KUBE_PS1_BINARY=oc

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ROS
source /opt/ros/melodic/setup.zsh

# Catkin
source /home/willer/catkin_ws/devel/setup.zsh

################## PROJECT ################
# source ~/.zshrc_current_project_name
