# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

ZPLUG_DIR=${ZPLUG_DIR:-$HOME/.zplug}
FZF_DIR=${FZF_DIR:-/usr/share/fzf}

# local bin
export PATH="$PATH:$HOME/.local/bin:$HOME/tools/bin"

source $ZPLUG_DIR/init.zsh
# Main theme
zplug "romkatv/powerlevel10k", as:theme, depth:1
# Vi mode in terminal
zplug "plugins/vi-mode", from:oh-my-zsh
# fish like syntax highlight
zplug "zsh-users/zsh-syntax-highlighting"
# fish like auto suggestion
zplug "zsh-users/zsh-autosuggestions"
# Jump to folder with Z
zplug "plugins/z", from:oh-my-zsh
# Move folder Ctrl+G
zplug "andrewferrier/fzf-z"
# Configure asdf
zplug "plugins/asdf", from:oh-my-zsh
# Automatic direnv
zplug "ptavares/zsh-direnv"

# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
zplug load

# zplug clean after plugin removal

################## SHELL ################

# History file
HISTFILE="$HOME/.zsh_history"
HISTSIZE=50000
SAVEHIST=10000

## History command configuration
setopt extended_history       # record timestamp of command in HISTFILE
setopt hist_expire_dups_first # delete duplicates first when HISTFILE size exceeds HISTSIZE
setopt hist_ignore_dups       # ignore duplicated commands history list
setopt hist_ignore_space      # ignore commands that start with space
setopt hist_verify            # show command with history expansion to user before running it
setopt inc_append_history     # add commands to HISTFILE in order of execution
setopt share_history          # share command history data
# Don't store command beginning with a space in history
setopt HIST_IGNORE_SPACE

# Automatically cd and push cd stack
setopt autocd autopushd pushdignoredups

# allow to do things like `ls *.png~not-this-file.png`
setopt extendedglob

export PAGER=less

# NeoVim as default editor
export EDITOR='nvim'

# Access vi-mode using jk
bindkey -M viins 'jk' vi-cmd-mode

# Reverse search with C-r
bindkey '^R' history-incremental-search-backward

################## ALIAS ################
alias ..='cd ..'
# Set LS_COLORS
eval `dircolors`
alias ls='ls --color'
alias la='ls --color -la'
alias l='ls --color -l'
alias ll='ls --color -l'
alias grep='grep --color=auto'
alias v=nvim
alias g=git
alias k=kubectl
alias tg=terragrunt
alias tf=terraform
alias asl='aws sso login'
alias sz='source ~/.zshrc'
alias sshgen='ssh-keygen -t ed25519'

# Get kubectl completion on alias
source <(kubectl completion zsh)
compdef __start_kubectl k
alias qgit="qgit --all&"
alias -g pingme="; notify-send JOB FINISHED"

################## TOOLS ################

# initialise completions with ZSH's compinit
autoload -Uz compinit && compinit

# FZF
[ -f $FZF_DIR/completion.zsh ] && source $FZF_DIR/completion.zsh && source $FZF_DIR/key-bindings.zsh

# Krew
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

# Kubernetes
[ -f ~/.kubectl_aliases ] && source ~/.kubectl_aliases

################## PROJECT ################
# source ~/.zshrc_current_project_name

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
